{% set name = "accessible-pygments" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7b57a9b15958e9601c7e9eb07a440c813283545a20973f2574a5f453d0e953e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - pygments
    - hatchling
    - hatch-vcs
    - setuptools-scm
  run:
    - python >=3.9
    - pygments

test:
  imports:
    - a11y_pygments.a11y_light
    - a11y_pygments.a11y_dark


about:
  home: https://github.com/Quansight-Labs/accessible-pygments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of accessible pygments styles
  description: |
    A collection of accessible pygments styles
  dev_url: https://github.com/Quansight-Labs/accessible-pygments

extra:
  recipe-maintainers:
    - carreau
    - trallard
