{% set name = "accessible-pygments" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 40918d3e6a2b619ad424cb91e556bd3bd8865443d9f22f1dcdf79e33c8046872

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - pygments
  run:
    - python >=3.6
    - pygments

test:
  imports:
    - a11y_pygments.a11y_light
    - a11y_pygments.a11y_dark


about:
  home: https://github.com/Quansight-Labs/accessible-pygments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of accessible pygments styles
  description: |
    A collection of accessible pygments styles
  dev_url: https://github.com/Quansight-Labs/accessible-pygments

extra:
  recipe-maintainers:
    - steff456
    - trallard
